### ISSUE TITLE
utility of Line 40

### ISSUE THREAD

**Issue by xavieras1** [amaotone/pygtm#3]
The whole code is awesome and very useful, but what's the utility of this line?
https://github.com/amaotone/pygtm/blob/0bb84ddac70e73ae94656a595967f52ca873dd72/pygtm/gtm.py#L40

**Comment by amaotone** [comment]
We want to calculate the `betainv2` by the average of nearest neighbors for each samples.
However, the diagonal components of `inter_dist` are the distance to themselves. So we have to fill the diagonal components by `np.inf` to calculate the distance to nearest "neighbor".
